; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
monitor_port = /dev/ttyUSB0
upload_protocol = espota
upload_port = gps-n2k.local
upload_flags = 
	--port=3232
	--auth=
lib_deps = 
	ttlappalainen/NMEA2000-library@^4.19.0
	https://github.com/sergei/NMEA2000_esp32_twai.git
	sparkfun/SparkFun u-blox GNSS v3@^3.1.5
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=0
platform_packages = espressif/toolchain-xtensa-esp32s3@8.4.0+2021r2-patch5
